export const INSERT_PERSON = 'INSERT_PERSON';
export const UPDATE_PERSON = 'UPDATE_PERSON';
export const EDIT_PERSON = 'EDIT_PERSON';
export const LIST_PERSON = 'LIST_PERSON';
export const REMOVE_PERSON = 'REMOVE_PERSON';
